// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"

	"encore.app/admin"
)

type BodyFatEntry struct {
	Date  string  `json:"date"`
	Value float64 `json:"value"`
}

type City struct {
	ID   int    `json:"id"`
	Name string `json:"name"`
}

type CompletedWorkout struct {
	ID       string   `json:"id"`
	Workout  *Workout `json:"workout"`
	Date     string   `json:"date"`
	Duration int      `json:"duration"`
	Notes    *string  `json:"notes,omitempty"`
	Rating   *int     `json:"rating,omitempty"`
}

type District struct {
	ID   int    `json:"id"`
	Name string `json:"name"`
}

type Exercise struct {
	ID          string  `json:"id"`
	Name        string  `json:"name"`
	Description string  `json:"description"`
	MuscleGroup *string `json:"muscleGroup,omitempty"`
	Equipment   *string `json:"equipment,omitempty"`
}

type Macros struct {
	Protein float64 `json:"protein"`
	Carbs   float64 `json:"carbs"`
	Fat     float64 `json:"fat"`
}

type MacrosInput struct {
	Protein float64 `json:"protein"`
	Carbs   float64 `json:"carbs"`
	Fat     float64 `json:"fat"`
}

type Meal struct {
	ID           string   `json:"id"`
	Name         string   `json:"name"`
	Description  string   `json:"description"`
	Ingredients  []string `json:"ingredients"`
	Instructions *string  `json:"instructions,omitempty"`
	Calories     int      `json:"calories"`
	Macros       *Macros  `json:"macros"`
	MealType     MealType `json:"mealType"`
}

type MealInput struct {
	Name         string       `json:"name"`
	Description  string       `json:"description"`
	Ingredients  []string     `json:"ingredients"`
	Instructions *string      `json:"instructions,omitempty"`
	Calories     int          `json:"calories"`
	Macros       *MacrosInput `json:"macros"`
	MealType     MealType     `json:"mealType"`
}

type MealPlan struct {
	ID          string   `json:"id"`
	Name        string   `json:"name"`
	Description string   `json:"description"`
	Meals       []*Meal  `json:"meals"`
	Calories    int      `json:"calories"`
	Macros      *Macros  `json:"macros"`
	CreatedBy   *Trainer `json:"createdBy,omitempty"`
}

type MealPlanInput struct {
	Name        string       `json:"name"`
	Description string       `json:"description"`
	Meals       []*MealInput `json:"meals"`
	Calories    int          `json:"calories"`
	Macros      *MacrosInput `json:"macros"`
}

type Message struct {
	ID        string      `json:"id"`
	Sender    *admin.User `json:"sender"`
	Content   string      `json:"content"`
	Timestamp string      `json:"timestamp"`
	IsRead    bool        `json:"isRead"`
}

type Mutation struct {
}

type NutritionLog struct {
	ID          string  `json:"id"`
	Meal        *Meal   `json:"meal"`
	Date        string  `json:"date"`
	Time        string  `json:"time"`
	PortionSize *string `json:"portionSize,omitempty"`
	Notes       *string `json:"notes,omitempty"`
}

type NutritionLogInput struct {
	MealID      string  `json:"mealId"`
	Date        string  `json:"date"`
	Time        string  `json:"time"`
	PortionSize *string `json:"portionSize,omitempty"`
	Notes       *string `json:"notes,omitempty"`
}

type ProgressMetrics struct {
	Weight   []*WeightEntry   `json:"weight"`
	BodyFat  []*BodyFatEntry  `json:"bodyFat"`
	Strength []*StrengthEntry `json:"strength"`
}

type ProgressPhoto struct {
	ID    string     `json:"id"`
	URL   string     `json:"url"`
	Date  string     `json:"date"`
	Notes *string    `json:"notes,omitempty"`
	Angle PhotoAngle `json:"angle"`
}

type Province struct {
	ID   int    `json:"id"`
	Name string `json:"name"`
}

type Query struct {
}

type StrengthEntry struct {
	ExerciseID string  `json:"exerciseId"`
	Date       string  `json:"date"`
	MaxWeight  float64 `json:"maxWeight"`
}

type Trainee struct {
	ID           string      `json:"id"`
	User         *admin.User `json:"user"`
	Age          int         `json:"age"`
	Height       float64     `json:"height"`
	Weight       float64     `json:"weight"`
	FitnessGoals []string    `json:"fitnessGoals"`
	Injuries     []string    `json:"injuries"`
	Preferences  []string    `json:"preferences"`
}

type TraineeInput struct {
	Age          *int     `json:"age,omitempty"`
	Height       *float64 `json:"height,omitempty"`
	Weight       *float64 `json:"weight,omitempty"`
	FitnessGoals []string `json:"fitnessGoals,omitempty"`
	Injuries     []string `json:"injuries,omitempty"`
	Preferences  []string `json:"preferences,omitempty"`
}

type Trainer struct {
	ID                string      `json:"id"`
	User              *admin.User `json:"user"`
	Specialization    []string    `json:"specialization"`
	YearsOfExperience int         `json:"yearsOfExperience"`
	Rating            *float64    `json:"rating,omitempty"`
}

type UserRegisterRequest struct {
	Username   string  `json:"username"`
	Email      string  `json:"email"`
	Password   string  `json:"password"`
	Fullname   string  `json:"fullname"`
	Address    *string `json:"address,omitempty"`
	ProvinceID *int    `json:"province_id,omitempty"`
	CityID     *int    `json:"city_id,omitempty"`
	DistrictID *int    `json:"district_id,omitempty"`
}

type WeightEntry struct {
	Date  string  `json:"date"`
	Value float64 `json:"value"`
}

type Workout struct {
	ID          string          `json:"id"`
	Name        string          `json:"name"`
	Description string          `json:"description"`
	Exercises   []*Exercise     `json:"exercises"`
	Duration    int             `json:"duration"`
	Difficulty  DifficultyLevel `json:"difficulty"`
	CreatedBy   *Trainer        `json:"createdBy,omitempty"`
}

type WorkoutLogInput struct {
	WorkoutID string  `json:"workoutId"`
	Duration  int     `json:"duration"`
	Notes     *string `json:"notes,omitempty"`
	Rating    *int    `json:"rating,omitempty"`
}

type DifficultyLevel string

const (
	DifficultyLevelBeginner     DifficultyLevel = "BEGINNER"
	DifficultyLevelIntermediate DifficultyLevel = "INTERMEDIATE"
	DifficultyLevelAdvanced     DifficultyLevel = "ADVANCED"
)

var AllDifficultyLevel = []DifficultyLevel{
	DifficultyLevelBeginner,
	DifficultyLevelIntermediate,
	DifficultyLevelAdvanced,
}

func (e DifficultyLevel) IsValid() bool {
	switch e {
	case DifficultyLevelBeginner, DifficultyLevelIntermediate, DifficultyLevelAdvanced:
		return true
	}
	return false
}

func (e DifficultyLevel) String() string {
	return string(e)
}

func (e *DifficultyLevel) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = DifficultyLevel(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid DifficultyLevel", str)
	}
	return nil
}

func (e DifficultyLevel) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *DifficultyLevel) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e DifficultyLevel) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type MealType string

const (
	MealTypeBreakfast MealType = "BREAKFAST"
	MealTypeLunch     MealType = "LUNCH"
	MealTypeDinner    MealType = "DINNER"
	MealTypeSnack     MealType = "SNACK"
)

var AllMealType = []MealType{
	MealTypeBreakfast,
	MealTypeLunch,
	MealTypeDinner,
	MealTypeSnack,
}

func (e MealType) IsValid() bool {
	switch e {
	case MealTypeBreakfast, MealTypeLunch, MealTypeDinner, MealTypeSnack:
		return true
	}
	return false
}

func (e MealType) String() string {
	return string(e)
}

func (e *MealType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = MealType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid MealType", str)
	}
	return nil
}

func (e MealType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *MealType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e MealType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type PhotoAngle string

const (
	PhotoAngleFront PhotoAngle = "FRONT"
	PhotoAngleSide  PhotoAngle = "SIDE"
	PhotoAngleBack  PhotoAngle = "BACK"
)

var AllPhotoAngle = []PhotoAngle{
	PhotoAngleFront,
	PhotoAngleSide,
	PhotoAngleBack,
}

func (e PhotoAngle) IsValid() bool {
	switch e {
	case PhotoAngleFront, PhotoAngleSide, PhotoAngleBack:
		return true
	}
	return false
}

func (e PhotoAngle) String() string {
	return string(e)
}

func (e *PhotoAngle) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = PhotoAngle(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid PhotoAngle", str)
	}
	return nil
}

func (e PhotoAngle) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *PhotoAngle) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e PhotoAngle) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
